name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install MinGW
      run: sudo apt update && sudo apt install -y mingw-w64 && sudo apt install -y gfortran-mingw-w64
    - name: checkout reference lapack
      run: git clone https://github.com/Reference-LAPACK/lapack.git && mkdir build
    - name: cmake
      run: cmake ../lapack -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER="x86_64-w64-mingw32-gcc" -DCMAKE_Fortran_COMPILER="x86_64-w64-mingw32-gfortran" -DBUILD_SHARED_LIBS=ON -DCBLAS=ON -DLAPACKE=ON -DCMAKE_BUILD_TYPE=Release
      working-directory: build
    - name: make
      run: make
      working-directory: build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: lapack-lib
        # Directory containing files to upload
        path: build
    
